sudo: required
services:
  - docker
before_install:
  - docker build -t zyadalatar/simple-app -f Dockerfile.dev .
script: 
  docker run zyadalatar/simple-app npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "me-south-1"
  app: "simple-app"
  env: "Simpleapp-env-1"
  bucket_name: "elasticbeanstalk-me-south-1-273560784509"
  bucket_path: "simple-app"
  on:
    branch: master
  access_key: "$aws_access_key"
  secret_access_key: 
    secure: "$aws_secret_access_key"
  